CREATE TABLE identity_challenges (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  purpose VARCHAR(24) NOT NULL,
  token_hash BINARY(32) NOT NULL,
  email_snapshot VARCHAR(254) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  expires_at DATETIME(6) NOT NULL,
  consumed_at DATETIME(6) NULL,
  revoked_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_challenges_token (token_hash),
  KEY idx_challenges_user_purpose (user_id, purpose, created_at),
  KEY idx_challenges_expiry (expires_at),
  CONSTRAINT fk_challenges_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT chk_challenges_purpose CHECK (purpose IN ('reset_password','activate_account')),
  CONSTRAINT chk_challenges_expiry CHECK (expires_at > created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE email_outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  challenge_id BIGINT UNSIGNED NULL,
  recipient VARCHAR(254) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  template_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  dedupe_key VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  encrypted_payload VARBINARY(8192) NULL,
  encryption_key_id VARCHAR(64) NULL,
  state VARCHAR(16) NOT NULL DEFAULT 'queued',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  available_at DATETIME(6) NOT NULL,
  expires_at DATETIME(6) NOT NULL,
  lease_owner VARCHAR(64) NULL,
  leased_until DATETIME(6) NULL,
  sent_at DATETIME(6) NULL,
  last_error_code VARCHAR(64) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_outbox_dedupe (dedupe_key),
  KEY idx_outbox_claim (state, available_at, id),
  KEY idx_outbox_lease (state, leased_until),
  CONSTRAINT fk_outbox_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_outbox_challenge FOREIGN KEY (challenge_id) REFERENCES identity_challenges(id) ON DELETE RESTRICT,
  CONSTRAINT chk_outbox_state CHECK (state IN ('queued','processing','sent','failed','cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
