export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  MISSING_ROUTE_POLICY: 'MISSING_ROUTE_POLICY',
  NOT_FOUND: 'NOT_FOUND',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  EMAIL_CONFLICT: 'EMAIL_CONFLICT',
  LAST_ADMIN_REQUIRED: 'LAST_ADMIN_REQUIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  CHALLENGE_INVALID: 'CHALLENGE_INVALID',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  CARD_NOT_ELIGIBLE: 'CARD_NOT_ELIGIBLE',
  NO_COPY_AVAILABLE: 'NO_COPY_AVAILABLE',
  ACTIVE_LOAN_LIMIT: 'ACTIVE_LOAN_LIMIT',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
